### ISSUE TITLE
Add Support for Conrad RSL Remote Sockets

### ISSUE THREAD

**Issue by raphaelmerz** [pimatic/rfcontroljs#121]
I have RSL Sockets from Conrad. Unfortunately I only ordered sockets without a remote control.
I've found a Website where someone wrote down the codes.
Please add this socket to the list.
http://www.forum-raspberrypi.de/Thread-tutorial-tutorial-radio-receiver-rsl366r-ansteuerung
Thanks

**Comment by mwittig** [comment]
Did you manage to successfully set this up with pimatic-homeduino? Which protocol are you using in case?

**Comment by raphaelmerz** [comment]
No I could'nt set it up. I don't know if the fault is somewhere by me. I tested almost every protocol with no sucess.

**Comment by mwittig** [comment]
I am closing this now. Please re-open if you wish to follow-up.
