### ISSUE TITLE
support for F007TH

### ISSUE THREAD

**Issue by gtortone** [pimatic/rfcontroljs#125]
Hi,
is it possible to add support for F007TH temperature/humidity sensor ?

some info here:
https://github.com/alex-konshin/f007th-rpi

**Comment by leader21** [comment]
Is there any debug data? If yes, for developing a detailed information on temp humidity and channel no. Is needed on multiple readings.

**Comment by gtortone** [comment]
ok,
I will try to collect sample data...
I found additional information on F007TH here:
http://www.osengr.org/WxShield/Downloads/Weather-Sensor-RF-Protocols.pdf

**Comment by mwittig** [comment]
No sample data provided. Closing
