### ISSUE TITLE
Request: Alecto WS-4500 Weather Station

### ISSUE THREAD

**Issue by Fritz4all** [pimatic/rfcontroljs#13]
I have the Alecto WS-4500 Weather Station and would like to add it to my Pimatic configuration : 

![ws-4500](https://cloud.githubusercontent.com/assets/7778422/4714090/ce4d0b1c-58ec-11e4-9963-443e38e2df76.jpg)

The set consists of : 
 - Teperature sensor
 - Humidity sensor
 - Wind speed sensor
 - Wind direction sensor
 - Rain fall sensor
 - Network Forecast Unit

-----------------------------------------------------------------------------------

Teperature sensor, Humidity sensor, Wind speed sensor, Wind direction sensor :

![winddirection](https://cloud.githubusercontent.com/assets/7778422/4714153/cf525264-58ed-11e4-8724-e78694dc2d3a.JPG)

Received : 
~~~
19:30:36.315 [pimatic-homeduino] debug: data: "RF receive 508 1977 3957 8925 0 0 0 0 01020201010201010101010102010102010102020101010101010201020202010202020103"
19:30:36.363 [pimatic-homeduino] debug: received: [ 508, 1977, 3957, 8925 ] 01020201010201010101010102010102010102020101010101010201020202010202020103
19:30:36.414 [pimatic-homeduino] debug: weather1:  { temperature: 77, humidity: 238 }

19:30:36.695 [pimatic-homeduino] debug: data: "RF receive 476 2006 3990 8976 0 0 0 0 01020201010201010101010102010102010102020101010101010201020202010202020103"
19:30:36.743 [pimatic-homeduino] debug: received: [ 476, 2006, 3990, 8976 ] 01020201010201010101010102010102010102020101010101010201020202010202020103
19:30:36.794 [pimatic-homeduino] debug: weather1:  { temperature: 77, humidity: 238 }
~~~

Rain fall meter : 

![rain](https://cloud.githubusercontent.com/assets/7778422/4714207/8b53f2b0-58ee-11e4-9525-cd08b35afad4.jpg)

~~~
20:48:25.017 [pimatic-homeduino] debug: data: "RF receive 502 4020 1991 9044 0 0 0 0 01010101020202010201010201010202010101010101020202020202020202020102020103"
20:48:25.054 [pimatic-homeduino] debug: received: [ 502, 1991, 4020, 9044 ] 02020202010101020102020102020101020202020202010101010101010101010201010203
20:48:25.088 [pimatic-homeduino] debug: weather1:  { temperature: 96, humidity: 9 }

20:49:01.614 [pimatic-homeduino] debug: data: "RF receive 532 3985 1966 9005 0 0 0 0 01010101020202010201010201010202010101010101020202020202020202020102020103"
20:49:01.650 [pimatic-homeduino] debug: received: [ 532, 1966, 3985, 9005 ] 02020202010101020102020102020101020202020202010101010101010101010201010203
20:49:01.688 [pimatic-homeduino] debug: weather1:  { temperature: 96, humidity: 9 }
~~~

Network Forecast Unit : 

![netwerk-unit](https://cloud.githubusercontent.com/assets/7778422/4714246/1d5ebafa-58ef-11e4-890c-edad75ed2fa3.jpg)

~~~
21:53:42.683 [pimatic-homeduino] debug: data: "RF receive 481 1013 2003 5957 0 0 0 0 0101010201010201010101010101010201010101010101010101010101010201010101010101020102020201020202010202010201010101010102010202010203"
21:53:42.754 [pimatic-homeduino] debug: received: [ 481, 1013, 2003, 5957 ] 0101010201010201010101010101010201010101010101010101010101010201010101010101020102020201020202010202010201010101010102010202010203

21:54:21.406 [pimatic-homeduino] debug: data: "RF receive 490 1003 1996 5949 0 0 0 0 0101010201010201010101010101010201010101010101010101010101010201010101010101020102020201020202010202010201010101010102010202010203"
21:54:21.446 [pimatic-homeduino] debug: received: [ 490, 1003, 1996, 5949 ] 0101010201010201010101010101010201010101010101010101010101010201010101010101020102020201020202010202010201010101010102010202010203

21:55:00.405 [pimatic-homeduino] debug: data: "RF receive 474 1018 2012 5994 0 0 0 0 0101010201010201010101010101010201010101010101010101010101010201010101010101020102020201020202010202010201010101010102010202010203"
21:55:00.446 [pimatic-homeduino] debug: received: [ 474, 1018, 2012, 5994 ] 0101010201010201010101010101010201010101010101010101010101010201010101010101020102020201020202010202010201010101010102010202010203
~~~

For a Complete Capture see Pastebin : 

http://pastebin.com/YxgZQm7Q

**Comment by Icesory** [comment]
Some news here?

**Comment by leader21** [comment]
i received the rainsensor and the anemometer last week.
the rainsensor seems to work but i'm having trouble to setup the anemometer.
seems that pimatic doesn't recognize it at all.

**Comment by incmve** [comment]
Everything seems to be working for me, the signal is really weak so I put another Pi in between to relay the data to my main Pi.

**Comment by leader21** [comment]
mine is approx 1 meter away from the pi. so i guess any data must be received or the anemometer is broken.

**Comment by leader21** [comment]
took the time to figure out the debug messages frm the homeduino plugin.
 (having 6 weather station devices in my rooms here, so there's a lot of debug output from homeduino, since the sensors create much rf traffic). i guess this here must be the anemometer since i checked out and compared all other weather sensor id's. could that be ?

![anemometer1](https://cloud.githubusercontent.com/assets/8620305/5792207/fedf8a00-9f0c-11e4-9264-93e2c83216d6.jpg)

i will take the device to the outside to see if the temp and hum. is changing. then this will be the confirmation.

**Comment by incmve** [comment]
Are you using the RFcontrol from @Icesory in your arduino?
https://github.com/Icesory/RFControl/tree/development

without that I only got temp and humidity, with the RFcontrol from Ronny I also get the wind.

**Comment by leader21** [comment]
aaah! ok, guess that's the point! 
will try it out later!

**Comment by leader21** [comment]
need some help to update the arduino.
i replaced the RFControl directory at the homeduino/libraries from ronny's development branch and did a "make upload". pimatic is still only displaying temp and hum from the anemometer. is there another thing alse that i need to consider? maybe to replace weather5.js with another version?

**Comment by incmve** [comment]
remove the build-nano directory and upload again.

**Comment by leader21** [comment]
sorry!! my bad! should have taken the development branch and cloned the master branch instead *facepalm*
now i get the correct debug output. thanks a lot for your quick help :) 
now i'll check the range of the device

**Comment by incmve** [comment]
lol been there XD

**Comment by leader21** [comment]
:+1:  :)
could you tell me if the the rain sensor is working properly? this little plastic thing doesn't look very trusty to me. and how did you set up the database storage? guess 1d should do, since an aggregation of the values for a longer time doesn't make any sense. actually i played a little with it and generated 5.75 mm rain. but tomorrow these 5.75mm will still be there and won't be of any useful information if not deleted somehow.  
at the other hand if there's no longer database saving, there's no more documentation of the rainfall for longer periods of time. 
well, that's actually beyond me :/

**Comment by incmve** [comment]
Rain is only reset when you take out the battery, so you could make a variable at 00:00 hours. 
```
IF it's  00:00 hours
THEN $rainyesterday = $weather-station.rain
```
The next day would be a rule
```
IF $weather-station.rain >= $rainyesterday 
THEN $raintoday = $weather-station.rain -  $rainyesterday 
```
 I don't use the rain unit. 

Windgust and windavg is constantly updated, I made a variable and a rule. 
```
IF $weather-station.windGust > $windgust 
THEN $windgust = $weather-station.windGust
```
And a button device to reset the $windgust variable

**Comment by Icesory** [comment]
Now are all parts of this are implemented in pimatic.

**Comment by homone73** [comment]
hello there.
I'm new and I need help.
I buy Alecto ws-4500, but I have a big problem I can not connect to my router.
netgear DGN2200v3, I followed everything that I was told from assistance, but nothing, can not give an IP address to the network adapter.
flashes 2 times for 5 seconds then it means that it is connected to the router but the router does not give him an IP address.
Have any of you had a similar experience? could you help me?
Thanks in advance

**Comment by incmve** [comment]
Yes it's because the network module has a MAC address of all zero's (00:00:00:00:00:00)
your router (most router) can't handle that because it isn't valid.

The only thing you can do is run a software DHCP server on your computer.
