### ISSUE TITLE
Protocol request: Eurodomest 972080

### ISSUE THREAD

**Issue by incmve** [pimatic/rfcontroljs#5]
I got this RF device, very cheap to get at Action.

I got this data from it, is it enough to get this in a protocol?
First run all buttons.

```
1 ON
RF receive 284 888 346 9660 0 0 0 0 01010110010101011010100110011001010101011010101002
1 OFF
RF receive 295 886 9626 0 0 0 0 0  01010110010101011010100110011001010101011010100102
2 ON
RF receive 294 887 9620 0 0 0 0 0 01010110010101011010100110011001010101011010011002
2 OFF
RF receive 294 887 9636 0 0 0 0 0 01010110010101011010100110011001010101011010010102
3 ON
RF receive 245 915 319 9621 0 0 0 0 01010110010101011010100110011001010101011001101002
3 OFF
RF receive 287 891 360 9621 0 0 0 0 01010110010101011010100110011001010101011001100102
4 ON
RF receive 289 892 9652 0 0 0 0 0 01010110010101011010100110011001010101010110101002
4 OFF
RF receive 291 891 9617 0 0 0 0 0 01010110010101011010100110011001010101010110100102
All ON
RF receive 282 892 357 9632 0 0 0 0 01010110010101011010100110011001010101010101100102
All OFF
RF receive 282 894 416 9604 0 0 0 0 01010110010101011010100110011001010101010101011002
```

![img 2014-10-14 13 10 42](https://cloud.githubusercontent.com/assets/3177116/4628189/e76f4dfc-5393-11e4-8d07-733a05a171c4.jpg)
![img 2014-10-14 13 10 16](https://cloud.githubusercontent.com/assets/3177116/4628188/e76a6ecc-5393-11e4-9a37-324afaf0c089.jpg)
![img 2014-10-14 13 10 30](https://cloud.githubusercontent.com/assets/3177116/4628190/e7737f3a-5393-11e4-803e-c670bd9a66ad.jpg)

**Comment by hansjeu** [comment]
Has anyone an working excample of how to put this in the config?

greetings Hans

**Comment by incmve** [comment]
```
{
      "id": "switch",
      "name": "switch",
      "class": "HomeduinoRFSwitch",
      "protocols": [
        {
          "name": "switch5",
          "options": {
            "id": 979295,
            "unit": 1
          }
        }
      ]
    }
```

**Comment by hansjeu** [comment]
Thank you.
This is not working. 
Is there a way to check if the transmitter is working?
And yes stupidly i bought only one set

Thanks

**Comment by incmve** [comment]
Maybe a stupid question from me but did you change the ID and unit in my example to your UD/unit?
If your still having problems please post in the forums http://forum.pimatic.org/

**Comment by hansjeu** [comment]
there are no stupid questions, just stupid people.
In this case me.
The ground-cable was faulty.
I have to resolder it.

Thank you very much

**Comment by grundel** [comment]
I just bought a set eurodomest 972080.
Checked the messages from the remote and added the device to config.json with the id and unit that I received.
When pushing the button in Pimatic I get a warning message, red circle with a cross, Oops..., unit is not defined.
These are my doings:

Message:

    2015-11-15 18:01:38debug [pimatic-homeduino]: doorbell1: { id: 1229, unit: 149, state: true }
    18:01:38debug [pimatic-homeduino]: led4: { id: 19669, command: 'code:01101111' }
    18:01:38debug [pimatic-homeduino]: contact3: { id: 733865, contact: false }
    18:01:38debug [pimatic-homeduino]: contact2: { id: 733865, contact: false }
    18:01:38debug [pimatic-homeduino]: switch15: { id: 314710, unit: 1, state: true, all: false }
    18:01:38debug [pimatic-homeduino]: switch14: { id: 314710, unit: 1, all: false, state: true }
    18:01:38debug [pimatic-homeduino]: switch5: { id: 733865, unit: 1, all: false, state: true }
    18:01:38debug [pimatic-homeduino]: received: [ 300, 880, 9584 ] 01100101101001011010011001100110011010011010101002
    18:01:38debug [pimatic-homeduino]: data: "RF receive 300 880 9584 0 0 0 0 0 01100101101001011010011001100110011010011010101002"


Device in config.json:

    {
      "id": "switch",
      "name": "switch",
      "class": "HomeduinoRFSwitch",
      "protocols": [
        {
          "name": "switch5",
          "options": {
            "id": 733865,
            "unit": 1
          }
        }
      ]
    }

What am I doing wrong?

**Comment by grundel** [comment]
After writing my last message I discovered a difference in the code of the switch5.js that was installed with the pimatic-arduino plugin and the switch5.js from the latest rfcontrol.
The one from the pimatic-arduino plugin contains the code:

      return "" + id + unit + "1012"

The one in the latest rfcontrol contains the code:

      return "" + id + unitCode + inverseState + "02";

After updating the switch5.js in the pimatic-arduino plugin it all works.

The working switch5.js code contains the following code :

module.exports = function(helper) {
  var binaryToPulse, protocolInfo, pulsesToBinaryMapping;
  pulsesToBinaryMapping = {
    '10': '0',
    '01': '1',
    '02': ''
  };
  binaryToPulse = {
    '0': '10',
    '1': '01'
  };
  return protocolInfo = {
    name: 'switch5',
    type: 'switch',
    values: {
      id: {
        type: "number"
      },
      all: {
        type: "number"
      },
      unit: {
        type: "number"
      },
      state: {
        type: "boolean"
      }
    },
    brands: ["Eurodomest"],
    pulseLengths: [295, 886, 9626],
    pulseCount: 50,
    decodePulses: function(pulses) {
      var all, binary, id, result, state, unit, unitCode;
      binary = helper.map(pulses, pulsesToBinaryMapping);
      id = helper.binaryToNumber(binary, 0, 19);
      unitCode = helper.binaryToNumber(binary, 20, 22);
      state = !helper.binaryToBoolean(binary, 23);
      all = false;
      unit = ((function() {
        switch (unitCode) {
          case 0:
            return 1;
          case 1:
            return 2;
          case 2:
            return 3;
          case 4:
            return 4;
          default:
            all = true;
            return 0;
        }
      })());
      if (all) {
        state = !state;
      }
      return result = {
        id: id,
        unit: unit,
        all: all,
        state: state
      };
    },
    encodeMessage: function(message) {
      var id, inverseState, state, unitCode;
      id = helper.map(helper.numberToBinary(message.id, 20), binaryToPulse);
      if (message.all) {
        unitCode = (message.state ? 6 : 7);
        state = !message.state;
      } else {
        unitCode = ((function() {
          switch (message.unit) {
            case 1:
              return 0;
            case 2:
              return 1;
            case 3:
              return 2;
            case 4:
              return 4;
          }
        })());
        state = message.state;
      }
      unitCode = helper.map(helper.numberToBinary(unitCode, 3), binaryToPulse);
      inverseState = (state ? binaryToPulse['0'] : binaryToPulse['1']);
      return "" + id + unitCode + inverseState + "02";
    }
  };
};

**Comment by pergola73** [comment]
This is just what I'm looking for. How can I update the switch5.js file on the pi? Where is it located?

txs!

**Comment by grundel** [comment]
Hi, pergola73,
switch5.js is located deep down in the pimatic-homeduino module.
Mine is located in:
/home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/rfcontroljs/lib/protocols/

Read, update, change by using WinSCP.
http://winscp.net/eng/download.php

Succes.

**Comment by Icesory** [comment]
You don't need to manually change the file, because it is in the master branch. You just need to update pimatic-homeduino and the actual rfcontroljs will be downloaded.
