### ISSUE TITLE
EV1527, RT1527, FP1527, HS1527 and HT12E decode

### ISSUE THREAD

**Issue by lcfm1** [pimatic/rfcontroljs#55]
you have code for decoding this protocol?

**Comment by mwittig** [comment]
@sweetpi Can please clarify if EV1527 is supported. Apparently, it is not. I found the following a bit confusing, as I wasn't sure about whether or not you have a device using EV1527 (the one shown on the pic).

**Comment by sweetpi** [comment]
The mention encodings are generally supported. However the chips are used with various oscilations (resulting in different pulse length) and different information encodings (resulting in different bits for unit and state information).

So we have to distinguish support for different devices, for though the same chips are used.
