### ISSUE TITLE
Switch1 dim support

### ISSUE THREAD

**Issue by koffienl** [pimatic/rfcontroljs#8]
For the KaKu brand we can use the switch1 protocol. Will there be support for dim values soon?
The KaKu protocol supports 15 steps of dim level.
When implementing a dimmer in the config, I would like to suggest to make it optional if a normall ON signal has to be send or allways send a full bright (100%) dim level to the device.

If needed, I can provide debug data from the receiver for the dimlevels.

**Comment by Icesory** [comment]
Are there some more questions open or can we close it?

**Comment by koffienl** [comment]
you can close this one AFAIK
